package install

import (
	"context"
	"fmt"
	"strings"

	"github.com/ggstudios/andersxn-os/installer/internal/provision"
)

// postInstallScript is the provisioning entry point inside the target.
const postInstallScript = "/usr/lib/andersxn/postinstall.sh"

// stepProvision deploys the selected homelab and developer stacks.
//
// The work itself is done by shell modules under /usr/lib/andersxn/modules,
// executed in the target chroot. Keeping them as scripts rather than Go code
// means an operator can re-run, read or fix any module on a live system with
// ax-provision(8), without a rebuild.
func (e *Engine) stepProvision(ctx context.Context) error {
	selected, added := provision.ResolveDependencies(e.Plan.Modules)
	if len(added) > 0 {
		e.logf("   pulled in dependencies: %s", strings.Join(added, ", "))
	}
	for _, w := range provision.Conflicts(selected) {
		e.logf("   warning: %s", w)
	}

	e.logf("provisioning: %s", strings.Join(selected, ", "))

	// Record the selection so ax-provision can re-run or extend it later, and
	// so a support bundle shows what the machine was built with.
	manifest := strings.Join(selected, "\n") + "\n"
	if err := e.writeFile(ctx, "/etc/andersxn/provision.d/selected", manifest, "0644"); err != nil {
		return err
	}

	// Open the ports the selection needs, in the dedicated nftables chain the
	// base ruleset already jumps to.
	if ports := provision.Ports(selected); len(ports) > 0 {
		var rules strings.Builder
		rules.WriteString("#!/usr/sbin/nft -f\n")
		rules.WriteString("# Generated by AX-Installer from the provisioning selection.\n")
		rules.WriteString("# Edit /etc/nftables.conf for permanent changes.\n\n")
		rules.WriteString("table inet axos {\n    chain services {\n")
		for _, port := range ports {
			owner := portOwner(selected, port)
			fmt.Fprintf(&rules, "        tcp dport %d accept comment \"%s\"\n", port, owner)
		}
		rules.WriteString("    }\n}\n")

		if err := e.writeFile(ctx, "/etc/nftables.d/10-axos-services.nft", rules.String(), "0644"); err != nil {
			return err
		}
		e.logf("   opened ports: %v", ports)
	}

	// The chroot needs working DNS to reach the Docker, Jellyfin and Tailscale
	// repositories. The live system's resolver is the only one available.
	script := fmt.Sprintf(`
cp -f /etc/resolv.conf.axos-install /etc/resolv.conf 2>/dev/null || true
export AXOS_MODULES=%s
export AXOS_USER=%s
export AXOS_NONINTERACTIVE=1
if [ -x %s ]; then
    %s
else
    echo "postinstall script missing at %s" >&2
    exit 1
fi
`,
		shellQuote(strings.Join(selected, " ")),
		shellQuote(e.Plan.Username),
		postInstallScript, postInstallScript, postInstallScript)

	if err := e.chrootScript(ctx, script); err != nil {
		return fmt.Errorf("provisioning: %w", err)
	}
	return nil
}

// portOwner names the module a port belongs to, for the nftables comment.
func portOwner(selected []string, port int) string {
	for _, id := range selected {
		mod, ok := provision.Lookup(id)
		if !ok {
			continue
		}
		for _, p := range mod.Ports {
			if p == port {
				return mod.ID
			}
		}
	}
	return "axos"
}
